version: "3.0"

services:
  database:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hyacinth
      - POSTGRES_DB=banking
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: